Remove publishing from push examples

diff --git a/gitlab-ci/.gitlab-ci-validation.yml b/gitlab-ci/.gitlab-ci-validation.yml
--- a/gitlab-ci/.gitlab-ci-validation.yml
+++ b/gitlab-ci/.gitlab-ci-validation.yml
@@ -8,7 +8,7 @@
     - if ! test -f ./executable/AIRAPP.exe; then echo "Executable does not exist." && exit 1; fi
 
 .check-and-publish: &check-and-publish
-    - $AIR/../utils/gitlab-runner/testcheck.py
+    - $UTILS/testcheck.py
     - $UTILS/publish_example.bash
 
 # ARM
@@ -30,7 +30,8 @@ ARM-QEMU-validation-test:
             ($UTILS/arm-ci.bash | tee testresult.txt) || true
           else
             ($UTILS/rvs_arm_coverage-ci.bash | tee testresult.txt) || true
-          fi 
+          fi
+
         - make distclean -i
         - *check-and-publish
     rules:
@@ -101,17 +102,16 @@ SPARC-LAYSIM-validation-test:
   script: 
         - cd $AIR/examples/private-example/private/validation/$EXAMPLE
         - *build-executable
-        - |
-          if [ "$CI_PIPELINE_SOURCE" = "schedule" ]; then
-            sshpass -p $PASSWORD2 scp executable/AIRAPP.exe gitlabrunner@$KNOWLI:/home/gitlabrunner && echo "File transfer successful." || echo "File transfer failed."
-            sshpass -p $PASSWORD2 scp $UTILS/gdb_sparc_rvs_coverage-ci gitlabrunner@$KNOWLI:/home/gitlabrunner && echo "File transfer successful." || echo "File transfer failed."
-            sshpass -p $PASSWORD2 scp $UTILS/target_cmds_eth_sparc.bash gitlabrunner@$KNOWLI:/home/gitlabrunner && echo "File transfer successful." || echo "File transfer failed."
-            script -c "sshpass -p $PASSWORD2 ssh -tt gitlabrunner@$KNOWLI 'bash -s < target_cmds_eth_sparc.bash $EXAMPLE'" testresult.txt
-            sshpass -p $PASSWORD2 scp gitlabrunner@$KNOWLI:/home/gitlabrunner/memdump.bin $AIR/examples/private-example/private/validation/$EXAMPLE && echo "File transfer successful." || echo "File transfer failed."
-            sshpass -p $PASSWORD2 scp gitlabrunner@$KNOWLI:/home/gitlabrunner/gdb_output.txt $AIR/examples/private-example/private/validation/$EXAMPLE && echo "File transfer successful." || echo "File transfer failed."
+        - if [ "$CI_PIPELINE_SOURCE" = "schedule" ]; then
+            sshpass -p $PASSWORD2 scp executable/AIRAPP.exe gitlabrunner@$KNOWLI:/home/gitlabrunner && echo "File transfer successful." || echo "File transfer failed.";
+            sshpass -p $PASSWORD2 scp $UTILS/gdb_sparc_rvs_coverage-ci gitlabrunner@$KNOWLI:/home/gitlabrunner && echo "File transfer successful." || echo "File transfer failed.";
+            sshpass -p $PASSWORD2 scp $UTILS/target_cmds_eth_sparc.bash gitlabrunner@$KNOWLI:/home/gitlabrunner && echo "File transfer successful." || echo "File transfer failed.";
+            script -c "sshpass -p $PASSWORD2 ssh -tt gitlabrunner@$KNOWLI 'bash -s < target_cmds_eth_sparc.bash $EXAMPLE'" testresult.txt;
+            sshpass -p $PASSWORD2 scp gitlabrunner@$KNOWLI:/home/gitlabrunner/memdump.bin $AIR/examples/private-example/private/validation/$EXAMPLE && echo "File transfer successful." || echo "File transfer failed.";
+            sshpass -p $PASSWORD2 scp gitlabrunner@$KNOWLI:/home/gitlabrunner/gdb_output.txt $AIR/examples/private-example/private/validation/$EXAMPLE && echo "File transfer successful." || echo "File transfer failed.";
             cat gdb_output.txt
           else
-            laysim-gr740-mmu-cli -batch $AIR/rvs_air/scripts/laysim_cmds.txt | tee testresult.txt
+            laysim-gr740-mmu-cli -batch $AIR/rvs_air/scripts/laysim_cmds.txt | tee testresult.txt;
           fi
         - make distclean -i # Ignore distclean errors
         - *check-and-publish
