[SPARC] Change validation tests script

diff --git a/gitlab-ci/.gitlab-ci-validation.yml b/gitlab-ci/.gitlab-ci-validation.yml
--- a/gitlab-ci/.gitlab-ci-validation.yml
+++ b/gitlab-ci/.gitlab-ci-validation.yml
@@ -102,7 +102,11 @@ SPARC-LAYSIM-validation-test:
         - cd $AIR/examples/private-example/private/validation/$EXAMPLE
         - *build-executable
         - if [ "$CI_PIPELINE_SOURCE" = "schedule" ]; then
-            *sparc-schedule
+            sshpass -p $PASSWORD2 scp executable/AIRAPP.exe gitlabrunner@$KNOWLI:/home/gitlabrunner && echo "File transfer successful." || echo "File transfer failed."
+            sshpass -p $PASSWORD2 scp $UTILS/gdb_sparc_rvs_coverage-ci.gdb gitlabrunner@$KNOWLI:/home/gitlabrunner && echo "File transfer successful." || echo "File transfer failed."
+            sshpass -p $PASSWORD2 scp $UTILS/target_cmds_eth_sparc.bash gitlabrunner@$KNOWLI:/home/gitlabrunner && echo "File transfer successful." || echo "File transfer failed."
+            script -c "sshpass -p $PASSWORD2 ssh -tt gitlabrunner@$KNOWLI 'bash -s < target_cmds_eth_sparc.bash'" testresult.txt
+            sshpass -p $PASSWORD2 scp gitlabrunner@$KNOWLI:/home/gitlabrunner/memdump.bin $AIR/examples/private-example/private/validation/$EXAMPLE && echo "File transfer successful." || echo "File transfer failed."
           else
             laysim-gr740-mmu-cli -batch $AIR/rvs_air/scripts/laysim_cmds.txt | tee testresult.txt
           fi
